import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

REPORT_DIR = "reports"
os.makedirs(REPORT_DIR, exist_ok=True)

def generate_medical_report(
    image_name,
    prediction,
    confidence,
    heatmap_path
):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_name = f"MedXScan_Report_{timestamp}.pdf"
    report_path = os.path.join(REPORT_DIR, report_name)

    c = canvas.Canvas(report_path, pagesize=A4)
    width, height = A4

    # ---------- TITLE ----------
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2, height - 50, "MedXScan AI – Medical Report")

    # ---------- META ----------
    c.setFont("Helvetica", 11)
    c.drawString(50, height - 100, f"Report Date: {datetime.now().strftime('%d-%m-%Y %H:%M')}")
    c.drawString(50, height - 120, f"X-ray File: {image_name}")

    # ---------- RESULTS ----------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 170, "Diagnosis Result")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 200, f"Predicted Disease: {prediction}")
    c.drawString(50, height - 220, f"Confidence Score: {round(confidence * 100, 2)}%")

    # ---------- HEATMAP ----------
    if os.path.exists(heatmap_path):
        c.drawImage(
            heatmap_path,
            50,
            height - 500,
            width=300,
            height=300,
            preserveAspectRatio=True
        )

    # ---------- REMARKS ----------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 540, "Medical Remarks")

    c.setFont("Helvetica", 11)
    c.drawString(
        50,
        height - 570,
        "This report is generated by an AI-assisted diagnostic system."
    )
    c.drawString(
        50,
        height - 590,
        "Results should be reviewed by a certified medical professional."
    )

    # ---------- FOOTER ----------
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(
        width / 2,
        40,
        "Generated by MedXScan AI | Not a substitute for clinical diagnosis"
    )

    c.showPage()
    c.save()

    return report_path
